version: '3.8'
services:
  datab:
    image: postgres:13.1
    container_name: food-db
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: foodgram_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  backend:
    container_name: food-backend
    image: stainy077/foodgram-backend:latest
    volumes:
      - static_data:/app/static/
      - media_data:/app/media/
    restart: always
    depends_on:
      - datab
    env_file:
      - .env

  frontend:
    container_name: food-frontend
    image: stainy077/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
      image: nginx:1.21.3-alpine
      container_name: food-nginx
      ports:
        - 8080:8080
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ../frontend/build:/usr/share/nginx/html/
        - ../docs/:/usr/share/nginx/html/api/docs/
        - static_data:/static/
        - media_data:/media/
      restart: always
      depends_on:
        - backend
        - frontend

volumes:
  database:
  static_data:
  media_data: